version: 2

sphinx:
  configuration: docs/conf.py
build:
  os: "ubuntu-lts-latest"
  tools:
    python: "latest"
  jobs:
    post_checkout:
    - git fetch --unshallow

python:
  install:
  - requirements: docs/requirements.txt
  - method: pip
    path: .
    extra_requirements:
    - doc
  - method: pip
    path: wrapper/
