version: 2.1
setup: true

orbs:
  path-filtering: circleci/path-filtering@3.0.0

workflows:
  setup:
    jobs:
      - path-filtering/filter:
          name: filter-paths
          base-revision: ${CIRCLE_BASE_REVISION:-master}
          mapping: |
            nibabies/.* run-build true
            Dockerfile run-build true
